### ISSUE TITLE
The implementation of `TrimToSize` in LruCache.java is different from pie framewrok's implementation. 

### ISSUE THREAD

**Issue by GerrieWell** [AndroidSDKSources/android-sdk-sources-for-api-level-28#1]
```java
//TrimToSize
                // BEGIN LAYOUTLIB CHANGE
                // get the last item in the linked list.
                // This is not efficient, the goal here is to minimize the changes
                // compared to the platform version.
                Map.Entry<K, V> toEvict = null;
                for (Map.Entry<K, V> entry : map.entrySet()) {
                    toEvict = entry;
                }
```

The `ToEvict` use the last element of The LinkedHashList. But it's the newest one. 
In Android 7.0 SDK code, It use LinkedHashMap#eldest to get `ToEvit`. And the func use header of the linkHashMap.

```java
    public Entry<K, V> eldest() {

        LinkedEntry<K, V> eldest = header.nxt;

        return eldest != header ? eldest : null;

    }
```

**Comment by flygoly** [comment]
@GerrieWell Thank you for you information.

**Comment by GerrieWell** [comment]
So do you mind to explain why there is difference implementation of `trimToSize` between android SDK source and android framework? 
https://android.googlesource.com/platform/frameworks/base/+/refs/heads/pie-release-2/core/java/android/util/LruCache.java
https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-28/blob/master/android/util/LruCache.java 

@ifeegoo
